import { Inter } from "next/font/google";
import '../assets/css/sb-admin-2.css'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-primary">{children}</body>
    </html>
  );
}
